# Generated by Django 2.0.7 on 2018-07-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20180727_2140'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Feedback',
        ),
    ]
