# Generated by Django 2.0.7 on 2018-07-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('N', 'Prefer Not to Mention')], max_length=1)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=70)),
                ('is_veg', models.BooleanField(default=True)),
                ('is_smoke', models.BooleanField(default=False)),
                ('is_alcohol', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=150)),
            ],
        ),
    ]
