# Generated by Django 2.0.7 on 2018-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_alcohol',
            field=models.CharField(choices=[('A', 'Alcoholic'), ('N', 'Non-Alcoholic')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_smoke',
            field=models.CharField(choices=[('S', 'Smoker'), ('N', 'Non-Smoker')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_veg',
            field=models.CharField(choices=[('V', 'Vegetarian'), ('N', 'Non-Vegetarian')], max_length=1),
        ),
    ]
