# Generated by Django 2.0.7 on 2018-07-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20180722_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='static/images/jpeg/user.jpg', upload_to='images/%d'),
        ),
    ]
